### ISSUE TITLE
Design main menu

### ISSUE THREAD

**Issue by Aritra-Paul** [cse442-spring-2020-offering/cse442-semester-project-ubnetdef#11]
### Task tests:

- Present an outline of the main menu in a digital format

**Comment by L1ghtman2k** [comment]
Task test:

Present main menu on initial application launch

**Comment by L1ghtman2k** [comment]
Outline of main menu:
![image.png](https://images.zenhubusercontent.com/5e2e128ddf0edc725da38e98/8db2bf9b-ac84-4aff-88be-b40a06c22109)
