### ISSUE TITLE
Research applicable SSH libraries on python

### ISSUE THREAD

**Issue by Aritra-Paul** [cse442-spring-2020-offering/cse442-semester-project-ubnetdef#2]
Task:
 - Select SSH library that will be used for baseline SSH class

**Comment by L1ghtman2k** [comment]
Task Test:
Remote into system that supports SSH using python

**Comment by L1ghtman2k** [comment]
Options: 
 - paramiko (baseline defacto ssh library for python)
 - fabric (flexible wrapper over paramiko)
 - https://github.com/ParallelSSH/parallel-ssh a more appealing ssh library due to its faster performance

**Comment by L1ghtman2k** [comment]
The final choice is parallel-ssh for superior speed and backward compatibility with windows
