### ISSUE TITLE
Module Selection in Menu Menu

### ISSUE THREAD

**Issue by Aritra-Paul** [cse442-spring-2020-offering/cse442-semester-project-ubnetdef#8]
### Story: 
As a developer, I want the application to have a way to select existing modules based on previously selected hosts to deploy on selected sets of hosts

### Acceptance Test:

- [x] Click `Ctrl+X` to open the main menu
- [x] Go to `Remote Hosts` Menu.
- [x] Select `Existing Hosts`, or `Add New Hosts`.
- [x] Submit the form (`Save` button)
- [x] Click `Ctrl+X` to open the main menu
- [x] Go to `Modules Menu`.
- [x] Select any of the `HTTP`
- [x] Select `Module 1`
- [x] Ensure that the selected module (`Module 1`) appears on the main screen

**Comment by L1ghtman2k** [comment]
Add modules dynamically might be impossible. Instead, load everything and utilize .hidden attribute: https://groups.google.com/forum/#!topic/npyscreen/yUr33oooLbI
